http:
  middlewares:
    chain-web-security-mdl:
      chain:
        middlewares:
          - header-web-security-mdl
          - ratelimit-webapp-mdl
          - compress-security-mdl
    
    header-web-security-mdl:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: >-
          camera=(), microphone=(), geolocation=(), payment=()
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - UPDATE
          - DELETE
          - PATCH
        accessControlAllowHeaders:
          - content-type
          - authorization
          - cache-control
          - x-requested-with
          - upload-source
          - x-session-id
          - x-lazy-pagination
          - x-disable-pagination
        accessControlMaxAge: 100
    
    ratelimit-webapp-mdl:
      rateLimit:
        average: 50
        burst: 200
        period: 1s

    compress-security-mdl:
      compress:
        excludedContentTypes:
          - text/event-stream
