all:
  children:
    prod:
      hosts:
        srv-dev-01:
          ansible_host: srv-dev-01.mshome.net
        srv-dev-02:
          ansible_host: srv-dev-02.mshome.net
      vars:
        ansible_user: demo
        ansible_ssh_private_key_file: /root/.ssh/private_key