- name: install packages
  hosts: prod
  become: true

  tasks:
    - name: install btop
      apt:
        name: btop
        state: present
        update_cache: true
    
    - name: start ssh server
      service:
        name: ssh
        state: started
        enabled: true